/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GameFloor {
    }
    interface GridMark {
        "cellSize": number;
        "xPosition": number;
        "yPosition": number;
    }
    interface GridMarks {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PlaySpace {
    }
}
declare global {
    interface HTMLGameFloorElement extends Components.GameFloor, HTMLStencilElement {
    }
    var HTMLGameFloorElement: {
        prototype: HTMLGameFloorElement;
        new (): HTMLGameFloorElement;
    };
    interface HTMLGridMarkElement extends Components.GridMark, HTMLStencilElement {
    }
    var HTMLGridMarkElement: {
        prototype: HTMLGridMarkElement;
        new (): HTMLGridMarkElement;
    };
    interface HTMLGridMarksElement extends Components.GridMarks, HTMLStencilElement {
    }
    var HTMLGridMarksElement: {
        prototype: HTMLGridMarksElement;
        new (): HTMLGridMarksElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPlaySpaceElement extends Components.PlaySpace, HTMLStencilElement {
    }
    var HTMLPlaySpaceElement: {
        prototype: HTMLPlaySpaceElement;
        new (): HTMLPlaySpaceElement;
    };
    interface HTMLElementTagNameMap {
        "game-floor": HTMLGameFloorElement;
        "grid-mark": HTMLGridMarkElement;
        "grid-marks": HTMLGridMarksElement;
        "my-component": HTMLMyComponentElement;
        "play-space": HTMLPlaySpaceElement;
    }
}
declare namespace LocalJSX {
    interface GameFloor {
    }
    interface GridMark {
        "cellSize"?: number;
        "xPosition"?: number;
        "yPosition"?: number;
    }
    interface GridMarks {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PlaySpace {
    }
    interface IntrinsicElements {
        "game-floor": GameFloor;
        "grid-mark": GridMark;
        "grid-marks": GridMarks;
        "my-component": MyComponent;
        "play-space": PlaySpace;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-floor": LocalJSX.GameFloor & JSXBase.HTMLAttributes<HTMLGameFloorElement>;
            "grid-mark": LocalJSX.GridMark & JSXBase.HTMLAttributes<HTMLGridMarkElement>;
            "grid-marks": LocalJSX.GridMarks & JSXBase.HTMLAttributes<HTMLGridMarksElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "play-space": LocalJSX.PlaySpace & JSXBase.HTMLAttributes<HTMLPlaySpaceElement>;
        }
    }
}
